namespace rei_esperantolib.Enums;

public enum E_ESPERANTO_EXCEPTION
{
    PROPRIEDADE_NAO_ENCONTRADA = 0,
    SOLICITACAO_COM_PENDENCIA = 1,
    IMPOSSIVEL_CONECTAR_COM_HOST = 2,
    PROPRIEDADE_NAO_ALTERADA = 3
}
